# config/services.yaml

# ...
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'

services:
    App\Controller\PayementController:
        autowire: true
    App\Security\UserAuthenticator:
        arguments:
            $urlGenerator: '@router.default' # Vous pouvez remplacer 'router.default' par le nom du service du routeur si nécessaire

