version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"  # Port pour l'interface Web de MailDev
      - "1025:25"  # Port pour le serveur SMTP de MailDev

volumes:
  database_data:

